In [1]:
import torch

In [14]:
#格式轉換

X=torch.arange(12).reshape(3,4)

A = X.numpy()
B = torch.tensor(A)

print ("A->",type(A),"\n",A)
print ("B->",type(B),"\n",B)

A-> <class 'numpy.ndarray'> 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
B-> <class 'torch.Tensor'> 
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [15]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [27]:
a = torch.tensor([[3.5,5,5.1]])
a[0,2], a[0,2].item(), float(a[0,2]), int(a[0,2])

(tensor(5.1000), 5.099999904632568, 5.099999904632568, 5)