In [1]:
import torch

In [6]:
X=torch.arange(12).reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [12]:
X[-1],X[-2],X[-3]

(tensor([ 8,  9, 10, 11]), tensor([4, 5, 6, 7]), tensor([0, 1, 2, 3]))

In [14]:
X[1,2],X[-1,-2]

(tensor(6), tensor(10))

In [15]:
X[1:3]

tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [17]:
X[-2:4]

tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [19]:
X[0:2,2]

tensor([2, 6])

In [20]:
X[0:2,0:2]

tensor([[0, 1],
        [4, 5]])