In [1]:
#2.1.1

import torch

x=torch.arange(12) 
print("torch.arange(12) ==>\n",x,"\n")

print("torch.arange(12).shape: ",x.shape) #the length along each axis

print("torch.arange(12).numel(): ",x.numel()) #the total number of elements in a tensor

print()
A=x.reshape([3,4]) #轉換成3*4的matirx
print("torch.arange(12).reshape([3,4])==>\n",A,"\n")

A=x.reshape([-1,4])
print("torch.arange(12).reshape([-1,4])==>\n",A,"\n")

a=torch.arange(20)
A=a.reshape(2,2,5)
print("torch.arange(20).reshape(2,2,5)==>\n",A,"\n")

A=torch.zeros([2,3,4])
print("torch.zeros([2,3,4])==>\n",A,"\n")

A=torch.ones([2,3,4])
print("torch.ones([2,3,4])==>\n",A,"\n")

A=torch.randn(3,4)
print("torch.randn(3,4)==>\n",A,"\n")

A=torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print("torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])==>\n",A,"\n")



torch.arange(12) ==>
 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]) 

torch.arange(12).shape:  torch.Size([12])
torch.arange(12).numel():  12

torch.arange(12).reshape([3,4])==>
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]) 

torch.arange(12).reshape([-1,4])==>
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]) 

torch.arange(20).reshape(2,2,5)==>
 tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]]) 

torch.zeros([2,3,4])==>
 tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]) 

torch.ones([2,3,4])==>
 tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]) 

torch.randn(3,4)==>
 tensor([[-1.7705, -1.6031, -0.8610, -0.

In [2]:
#2.1.2

x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

print("x ==>\n",x,"\n")
print("y ==>\n",y,"\n")
print("x+y ==>\n",x+y,"\n")
print("x-y ==>\n",x-y,"\n")
print("x*y ==>\n",x*y,"\n")
print("x/y ==>\n",x/y,"\n")
print("x**y ==>\n",x**y,"\n")
print("e^x ==>\n",torch.exp(x),"\n")


X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print("X ==>\n",X,"\n")
print("Y ==>\n",Y,"\n")

print("以row把X跟Y作合併 ==>\n",torch.cat((X, Y), dim=0),"\n")
print("以col把X跟Y作合併 ==>\n",torch.cat((X, Y), dim=1),"\n")
print("X==Y ==>\n",X==Y,"\n")
print("X的element總和 ==>\n",X.sum(),"\n")


x ==>
 tensor([1., 2., 4., 8.]) 

y ==>
 tensor([2, 2, 2, 2]) 

x+y ==>
 tensor([ 3.,  4.,  6., 10.]) 

x-y ==>
 tensor([-1.,  0.,  2.,  6.]) 

x*y ==>
 tensor([ 2.,  4.,  8., 16.]) 

x/y ==>
 tensor([0.5000, 1.0000, 2.0000, 4.0000]) 

x**y ==>
 tensor([ 1.,  4., 16., 64.]) 

e^x ==>
 tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03]) 

X ==>
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]) 

Y ==>
 tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]]) 

以row把X跟Y作合併 ==>
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]]) 

以col把X跟Y作合併 ==>
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]) 

X==Y ==>
 tensor([[False,  True, False,  True],
        [False, False, False, False],
        [Fa

In [3]:
#2.1.3

a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
print("a ==>\n",a,"\n")
print("b ==>\n",b,"\n")

print("a+b ==>\n",a+b,"\n") #會對matrix進行拓展做運算

a ==>
 tensor([[0],
        [1],
        [2]]) 

b ==>
 tensor([[0, 1]]) 

a+b ==>
 tensor([[0, 1],
        [1, 2],
        [2, 3]]) 



In [4]:
#2.1.4

X=torch.arange(12).reshape(3,4)
print("X ==>\n",X,"\n")

print("X[-1] ==>\n",X[-1],"\n")
print("X[-2] ==>\n",X[-2],"\n")
print("X[-3] ==>\n",X[-3],"\n")

print("X[1,2] ==>\n",X[1,2],"\n")
print("X[-1,-2] ==>\n",X[-1,-2],"\n")

print("X[1:3] ==>\n",X[1:3],"\n")
print("X[-2:4] ==>\n",X[-2:4],"\n")

print("X[0:2,2] ==>\n",X[0:2,2],"\n")
print("X[0:2,0:2] ==>\n",X[0:2,0:2],"\n")


X ==>
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]) 

X[-1] ==>
 tensor([ 8,  9, 10, 11]) 

X[-2] ==>
 tensor([4, 5, 6, 7]) 

X[-3] ==>
 tensor([0, 1, 2, 3]) 

X[1,2] ==>
 tensor(6) 

X[-1,-2] ==>
 tensor(10) 

X[1:3] ==>
 tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]) 

X[-2:4] ==>
 tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]) 

X[0:2,2] ==>
 tensor([2, 6]) 

X[0:2,0:2] ==>
 tensor([[0, 1],
        [4, 5]]) 



In [5]:
#2.1.5

X=torch.arange(12).reshape(3,4)
Y=torch.tensor([[2,1,4,3],[0,1,2,3],[4,5,6,7]])
print("X ==>\n",X,"\n")
print("Y ==>\n",Y,"\n")

before = id(Y) #Y的位址
Y = Y + X
print("Y=Y+X後, Y的新位址跟舊位址一不一樣? ==>\n",id(Y) == before,"\n")

Z = torch.zeros_like(Y)
print("Z ==>\n",Z,"\n")
print("id(Z): ", id(Z),"\n")

Z[:] = X + Y
print("Z ==>\n",Z,"\n")
print("id(Z): ", id(Z),"\n")

before = id(X)
X += Y
print("X+=Y後, X的新位址跟舊位址一不一樣? ==>\n",id(X) == before,"\n")


X ==>
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]) 

Y ==>
 tensor([[2, 1, 4, 3],
        [0, 1, 2, 3],
        [4, 5, 6, 7]]) 

Y=Y+X後, Y的新位址跟舊位址一不一樣? ==>
 False 

Z ==>
 tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]) 

id(Z):  140210862680192 

Z ==>
 tensor([[ 2,  3,  8,  9],
        [ 8, 11, 14, 17],
        [20, 23, 26, 29]]) 

id(Z):  140210862680192 

X+=Y後, X的新位址跟舊位址一不一樣? ==>
 True 



In [6]:
#2.1.6

#格式轉換

X=torch.arange(12).reshape(3,4)
print("torch.arange(12).reshape(3,4) ==>\n",X,"\n")

A = X.numpy()
B = torch.tensor(A)

print("torch.arange(12).reshape(3,4).numpy() ==>\n",A,"\n")
print("type :\n",type(A),"\n")
print("torch.tensor(torch.arange(12).reshape(3,4).numpy()) ==>\n",B,"\n")
print("type :\n",type(B),"\n")

a = torch.tensor([3.5])
print("torch.tensor([3.5]) ==>\n",a,"\n")
print("torch.tensor([3.5]).item() ==>\n",a.item(),"\n")
print("float(torch.tensor([3.5])) ==>\n",float(a),"\n")
print("int(torch.tensor([3.5])) ==>\n",int(a),"\n")

a = torch.tensor([[3.5,5,5.1]])
print("torch.tensor([[3.5,5,5.1]]) ==>\n",a,"\n")
print("torch.tensor([[3.5,5,5.1]])[0,2] ==>\n",a[0,2],"\n")
print("torch.tensor([[3.5,5,5.1]])[0,2].item() ==>\n",a[0,2].item(),"\n")
print("float(torch.tensor([[3.5,5,5.1]])[0,2]) ==>\n",float(a[0,2]),"\n")
print("int(torch.tensor([[3.5,5,5.1]])[0,2]) ==>\n",int(a[0,2]),"\n")


torch.arange(12).reshape(3,4) ==>
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]) 

torch.arange(12).reshape(3,4).numpy() ==>
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

type :
 <class 'numpy.ndarray'> 

torch.tensor(torch.arange(12).reshape(3,4).numpy()) ==>
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]) 

type :
 <class 'torch.Tensor'> 

torch.tensor([3.5]) ==>
 tensor([3.5000]) 

torch.tensor([3.5]).item() ==>
 3.5 

float(torch.tensor([3.5])) ==>
 3.5 

int(torch.tensor([3.5])) ==>
 3 

torch.tensor([[3.5,5,5.1]]) ==>
 tensor([[3.5000, 5.0000, 5.1000]]) 

torch.tensor([[3.5,5,5.1]])[0,2] ==>
 tensor(5.1000) 

torch.tensor([[3.5,5,5.1]])[0,2].item() ==>
 5.099999904632568 

float(torch.tensor([[3.5,5,5.1]])[0,2]) ==>
 5.099999904632568 

int(torch.tensor([[3.5,5,5.1]])[0,2]) ==>
 5 

