In [1]:
import torch

In [6]:
X=torch.arange(12).reshape(3,4)
Y=torch.tensor([[0,1,2,3],[1,2,3,4],[1,3,5,7]])
print("X->\n",X)
print("Y->\n",Y)

X->
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Y->
 tensor([[0, 1, 2, 3],
        [1, 2, 3, 4],
        [1, 3, 5, 7]])


In [7]:
X==Y

tensor([[ True,  True,  True,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [8]:
X<Y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [9]:
X>Y

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [10]:
X!=Y

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])