In [1]:
import torch

In [20]:
a = torch.arange(1, 9).reshape((2,2,2))
b = torch.arange(1, 3).reshape((1, 2))

In [21]:
print ("a->\n",a)
print ("b->\n",b)

a->
 tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
b->
 tensor([[1, 2]])


In [22]:
a+b

tensor([[[ 2,  4],
         [ 4,  6]],

        [[ 6,  8],
         [ 8, 10]]])

In [23]:
a-b

tensor([[[0, 0],
         [2, 2]],

        [[4, 4],
         [6, 6]]])

In [24]:
a*b

tensor([[[ 1,  4],
         [ 3,  8]],

        [[ 5, 12],
         [ 7, 16]]])

In [25]:
a/b

tensor([[[1., 1.],
         [3., 2.]],

        [[5., 3.],
         [7., 4.]]])

In [26]:
a**b

tensor([[[ 1,  4],
         [ 3, 16]],

        [[ 5, 36],
         [ 7, 64]]])