In [1]:
# 5.4. Custom Layers
# 5.4.1. Layers without Parameters
import torch
from torch import nn
from torch.nn import functional as F

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [2]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

In [4]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(-6.5193e-09, grad_fn=<MeanBackward0>)

In [5]:
# 5.4.2. Layers with Parameters
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [6]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 1.7119,  1.3689,  0.8176],
        [ 0.5065,  0.8996,  0.1553],
        [ 1.2137, -0.9983, -0.7896],
        [ 0.3699,  0.3879,  1.7103],
        [ 0.2090,  0.8301, -0.7241]], requires_grad=True)

In [7]:
linear(torch.rand(2, 5))

tensor([[3.5689, 2.0245, 2.3093],
        [2.3246, 1.9541, 0.2979]])

In [8]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[12.7750],
        [14.5461]])