In [1]:
# 5.6. GPUs
!nvidia-smi

zsh:1: command not found: nvidia-smi


In [2]:
# 5.6.1. Computing Devices
import torch
from torch import nn

torch.device('cpu'), torch.device('cuda'), torch.device('cuda:1')

(device(type='cpu'), device(type='cuda'), device(type='cuda', index=1))

In [3]:
torch.cuda.device_count()

0

In [4]:
def try_gpu(i=0):  #@save
    """Return gpu(i) if exists, otherwise return cpu()."""
    if torch.cuda.device_count() >= i + 1:
        return torch.device(f'cuda:{i}')
    return torch.device('cpu')

def try_all_gpus():  #@save
    """Return all available GPUs, or [cpu(),] if no GPU exists."""
    devices = [
        torch.device(f'cuda:{i}') for i in range(torch.cuda.device_count())]
    return devices if devices else [torch.device('cpu')]

try_gpu(), try_gpu(10), try_all_gpus()

(device(type='cpu'), device(type='cpu'), [device(type='cpu')])

In [5]:
# 5.6.2. Tensors and GPUs
x = torch.tensor([1, 2, 3])
x.device

device(type='cpu')

In [6]:
# 5.6.2.1. Storage on the GPU
X = torch.ones(2, 3, device=try_gpu())
X

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
Y = torch.rand(2, 3, device=try_gpu(1))
Y

tensor([[0.1925, 0.8799, 0.9071],
        [0.6740, 0.0132, 0.4542]])

In [9]:
# 5.6.3. Neural Networks and GPUs
net = nn.Sequential(nn.Linear(3, 1))
net = net.to(device=try_gpu())

In [10]:
net(X)

tensor([[0.5809],
        [0.5809]], grad_fn=<AddmmBackward>)

In [11]:
net[0].weight.data.device

device(type='cpu')