In [1]:
import torch

x = torch.arange(20).reshape(5, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [2]:
x.T #轉置

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [8]:
x=torch.tensor([[1,2,3],[2,4,14],[3,2,1]])
x

tensor([[ 1,  2,  3],
        [ 2,  4, 14],
        [ 3,  2,  1]])

In [9]:
x==x.T #維度要一樣才可以比較

tensor([[ True,  True,  True],
        [ True,  True, False],
        [ True, False,  True]])