In [6]:
import torch

#2.3.1

x=torch.tensor(3)
y=torch.tensor(2)

print("x ==>\n",x,"\n")
print("y ==>\n",y,"\n")
print("x+y ==>\n",x+y,"\n")
print("x-y ==>\n",x-y,"\n")
print("x*y ==>\n",x*y,"\n")
print("x/y ==>\n",x/y,"\n")
print("x**y ==>\n",x**y,"\n")


x ==>
 tensor(3) 

y ==>
 tensor(2) 

x+y ==>
 tensor(5) 

x-y ==>
 tensor(1) 

x*y ==>
 tensor(6) 

x/y ==>
 tensor(1.5000) 

x**y ==>
 tensor(9) 



In [7]:
#2.3.2

x=torch.arange(4)
print("x ==>\n",x,"\n")

x=torch.arange(2,5)
print("x ==>\n",x,"\n")

print("x[2] ==>\n",x[2],"\n")
print("len(x) ==>\n",len(x),"\n")
print("x.shape ==>\n",x.shape,"\n")


x ==>
 tensor([0, 1, 2, 3]) 

x ==>
 tensor([2, 3, 4]) 

x[2] ==>
 tensor(4) 

len(x) ==>
 3 

x.shape ==>
 torch.Size([3]) 



In [8]:
#2.3.3

x = torch.arange(20).reshape(5, 4)
print("x ==>\n",x,"\n")

print("x的轉置矩陣 ==>\n",x.T,"\n") #轉置


x=torch.tensor([[1,2,3],[2,4,14],[3,2,1]])
print("x ==>\n",x,"\n")

print("x==x.T ==>\n",x==x.T,"\n") #維度要一樣才可以比較

x ==>
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]]) 

x的轉置矩陣 ==>
 tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]]) 

x ==>
 tensor([[ 1,  2,  3],
        [ 2,  4, 14],
        [ 3,  2,  1]]) 

x==x.T ==>
 tensor([[ True,  True,  True],
        [ True,  True, False],
        [ True, False,  True]]) 



In [9]:
#2.3.4

x = torch.arange(3,27).reshape(2, 3, 4)
print("x ==>\n",x,"\n")

x ==>
 tensor([[[ 3,  4,  5,  6],
         [ 7,  8,  9, 10],
         [11, 12, 13, 14]],

        [[15, 16, 17, 18],
         [19, 20, 21, 22],
         [23, 24, 25, 26]]]) 



In [10]:
#2.3.5

A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # Assign a copy of `A` to `B` by allocating new memory

print("A ==>\n",A,"\n")
print("B ==>\n",B,"\n")
print("A+B ==>\n",A+B,"\n")
print("A*B ==>\n",A*B,"\n")

a = 2
X = torch.arange(24).reshape(2, 3, 4)
print("a ==>\n",a,"\n")
print("X ==>\n",X,"\n")
print("a+X ==>\n",a+X,"\n")
print("a*X ==>\n",a*X,"\n")
print("(a*X).shape ==>\n",(a*X).shape,"\n")
print("X.sum() ==>\n",X.sum(),"\n")
print("X.sum(axis=[0,1]) ==>\n",X.sum(axis=[0,1]),"\n")
print("X.sum(axis=0) ==>\n",X.sum(axis=0),"\n")
print("X.sum(axis=1) ==>\n",X.sum(axis=1),"\n")
print("X.sum(axis=2) ==>\n",X.sum(axis=2),"\n")
print("X.sum()/X.numel() ==>\n",X.sum() / X.numel(),"\n")
print("X.shape[0] ==>\n",X.shape[0],"\n")


A ==>
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) 

B ==>
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) 

A+B ==>
 tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]]) 

A*B ==>
 tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]]) 

a ==>
 2 

X ==>
 tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]) 

a+X ==>
 tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
    