In [6]:
import torch

#1. Prove that the transpose of a matrix A's transpose is A: (A^T)^T==A 
A=torch.arange(12).reshape([3,4])
A.T.T==A

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [9]:
#2. Given two matrices A and B, show that the sum of transposes is equal to the transpose of a sum: A^T+B^T=(A+B)^T
B=torch.arange(5,17).reshape([3,4])
(A+B).T==A.T+B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True]])

In [16]:
#3. Given any square matrix A, is A+A^T always symmetric? Why?
A=torch.arange(9).reshape([3,3])
A+A.T==(A+A.T).T
print("yes, 因為transpose後相加的兩數都一樣")

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [19]:
#4. We defined the tensor X of shape (2, 3, 4) in this section. What is the output of len(X)?
X=torch.arange(24).reshape(2,3,4)
len(X)

2

In [20]:
#5. For a tensor X of arbitrary shape, does len(X) always correspond to the length of a certain axis of X? What is that axis?
print("len()取的是第一個dimension")

len()取的是第一個dimension


In [33]:
#6. Run A / A.sum(axis=1) and see what happens. Can you analyze the reason?
A=torch.arange(20).reshape(5,4)
print("A==>\n",A)
print("\nA.sum(axis=1)==>\n",A.sum(axis=1))
#print("\nA / A.sum(axis=1)==>\n",A / A.sum(axis=1))

print("因為sum(axis=1)是把row的值加在一起,會產生1*5的matrix,沒辦法跟A(5*4)做除法")

print("\nA==>\n",A)
print("\nA.sum(axis=1)==>\n",A.sum(axis=0))
print("\nA / A.sum(axis=1)==>\n",A / A.sum(axis=0))

print("\n如果改成sum(axis=0),把column的值加在一起,會產生1*4的matrix,就沒有問題了！")


A==>
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

A.sum(axis=1)==>
 tensor([ 6, 22, 38, 54, 70])
因為sum(axis=1)是把row的值加在一起,會產生1*5的matrix,沒辦法跟A(5*4)做除法

A==>
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

A.sum(axis=1)==>
 tensor([40, 45, 50, 55])

A / A.sum(axis=1)==>
 tensor([[0.0000, 0.0222, 0.0400, 0.0545],
        [0.1000, 0.1111, 0.1200, 0.1273],
        [0.2000, 0.2000, 0.2000, 0.2000],
        [0.3000, 0.2889, 0.2800, 0.2727],
        [0.4000, 0.3778, 0.3600, 0.3455]])

如果改成sum(axis=0),把column的值加在一起,會產生1*4的matrix,就沒有問題了！


8. Consider a tensor with shape (2, 3, 4). What are the shapes of the summation outputs along axis 0, 1, and 2?
print("X==>\n",X)
print("\nX.sum(axis=0)==>\n",X.sum(axis=0))
print("\nX.sum(axis=1)==>\n",X.sum(axis=1))
print("\nX.sum(axis=2)==>\n",X.sum(axis=2))

In [36]:
#8. Consider a tensor with shape (2, 3, 4). What are the shapes of the summation outputs along axis 0, 1, and 2?
print("X==>\n",X) 
print("\nX.sum(axis=0)==>\n",X.sum(axis=0))
print("\nX.sum(axis=1)==>\n",X.sum(axis=1))
print("\nX.sum(axis=2)==>\n",X.sum(axis=2))

X==>
 tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

X.sum(axis=0)==>
 tensor([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]])

X.sum(axis=1)==>
 tensor([[12, 15, 18, 21],
        [48, 51, 54, 57]])

X.sum(axis=2)==>
 tensor([[ 6, 22, 38],
        [54, 70, 86]])


In [40]:
#9. Feed a tensor with 3 or more axes to the linalg.norm function and observe its output. What does this function compute for tensors of arbitrary shape?
Y= torch.arange(24,dtype = torch.float32).reshape(2, 3, 4)
print(torch.norm(Y))

i = 0
for j in range(0,24):
    i += j**2

import math
print(math.sqrt(i))
print("對matrix中每個element平方加起來再開根號")

tensor(65.7571)
65.75712889109438
對matrix中每個element平方加起來再開根號
