In [1]:
#2.2.1

import os
import torch
import pandas as pd

#讀取dataset

os.makedirs(os.path.join('.', 'data'), exist_ok=True)
data_path = os.path.join('.', 'data', 'house_tiny.csv')

with open(data_path, 'w', encoding="utf-8") as data_file:
    data_file.write('NumRooms,Alley,Price\n')  # Column names
    data_file.write('NA,Pave,127500\n')  # Each row represents a data example
    data_file.write('2,NA,106000\n')
    data_file.write('4,NA,178100\n')
    data_file.write('NA,NA,140000\n')
    
data = pd.read_csv(data_path)
print(data)
print()

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000



In [2]:
#2.2.2

inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2] #用iloc提取column
inputs_1 = inputs.fillna(2) #用2取代nan
print(inputs_1)
print()

inputs_2 = inputs.fillna(inputs.mean()) #用平均值取代nan
print(inputs_2)
print()

inputs = pd.get_dummies(inputs, dummy_na=True) #將種類提到標題,用boolean表示
print(inputs)
print()

   NumRooms Alley
0       2.0  Pave
1       2.0     2
2       4.0     2
3       2.0     2

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

   NumRooms  Alley_Pave  Alley_nan
0       NaN           1          0
1       2.0           0          1
2       4.0           0          1
3       NaN           0          1



In [4]:
#2.2.3


print("inputs.values==>\n",inputs.values,"\n")
print("outputs.values==>\n",outputs.values,"\n")

#格式轉換 dataframe->tensor

print("torch.tensor(inputs.values)==>\n",torch.tensor(inputs.values),"\n")
print("torch.tensor(outputs.values)==>\n",torch.tensor(outputs.values),"\n")



inputs.values==>
 [[nan  1.  0.]
 [ 2.  0.  1.]
 [ 4.  0.  1.]
 [nan  0.  1.]] 

outputs.values==>
 [127500 106000 178100 140000] 

torch.tensor(inputs.values)==>
 tensor([[nan, 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [nan, 0., 1.]], dtype=torch.float64) 

torch.tensor(outputs.values)==>
 tensor([127500, 106000, 178100, 140000]) 

